# Introduction to Torch Tensors

- In order to do machine learning, objects in real life must be transformed to numbers.
- This numbers are usually grouped in structures, so we need to store them together in some particular order

## Tensors
A tensor is a multidimensional array.
- Is the basic building block of most deep learning frameworks

Tensors can have from 0 to n dimensions.

In [3]:
import torch

# scalars
t = torch.tensor(3)
t, t.shape

(tensor(3), torch.Size([]))

In [4]:
# 1D tensor
t = torch.tensor([2, 3, 4])
t, t.shape

(tensor([2, 3, 4]), torch.Size([3]))

In [5]:
t = torch.tensor([2, 3, 4, 5, 6, 7, 8])
t, t.shape

(tensor([2, 3, 4, 5, 6, 7, 8]), torch.Size([7]))

In [6]:
# 2D tensor

t = torch.tensor(
    [
        [2, 3, 4], 
        [6, 7, 8]
    ])
t, t.shape

(tensor([[2, 3, 4],
         [6, 7, 8]]),
 torch.Size([2, 3]))

In [7]:
# Higher dimensional tensors
t = torch.randn((3, 4, 5))
t, t.shape

(tensor([[[ 0.4849, -0.2978,  2.1928,  1.7069, -0.5734],
          [-0.2688, -0.2013, -1.0209, -0.8596,  0.4114],
          [-0.8720,  0.9353,  0.6298, -0.9107,  1.1841],
          [-0.3651,  1.2067,  1.7885, -0.1640, -0.4692]],
 
         [[ 0.1680,  1.1181,  0.8991, -1.4601,  0.2847],
          [-2.0889,  0.1075,  0.1416,  0.1408,  2.0412],
          [-2.4949, -0.9284,  0.0093, -0.8064, -0.9253],
          [ 0.5416,  0.0896,  0.9436, -0.4527, -0.1089]],
 
         [[ 0.4913,  0.4147,  1.2459,  1.4788, -0.6223],
          [-0.2533, -1.1773, -0.6648,  0.1009,  1.6204],
          [ 1.1659, -1.7670, -0.2197, -0.7643,  0.0406],
          [-0.3928, -0.2757,  0.3955,  1.3893, -0.2553]]]),
 torch.Size([3, 4, 5]))

In [8]:
# Higher dimensional tensors
t = torch.randn((2, 3, 4, 5))
t, t.shape

(tensor([[[[-0.9511,  0.1512, -0.0730, -1.0974, -2.3081],
           [-1.3377,  0.3924,  0.8740,  0.1241, -1.8223],
           [ 2.0369,  0.1233,  1.7726, -1.7495,  1.4602],
           [-0.1792,  0.8228,  0.3390, -0.1799, -0.2058]],
 
          [[-1.6956, -0.5193,  0.2448,  0.9190,  0.4873],
           [ 0.7054, -0.1288,  0.6972, -0.6431, -0.1054],
           [ 1.3413,  0.8851, -1.1937,  1.2053, -0.7322],
           [ 1.4906, -0.6133,  0.1109,  0.1912,  0.1651]],
 
          [[-0.0418, -1.4620,  0.4339,  0.5949, -0.4619],
           [-0.2756, -0.4619, -0.2439,  0.8598,  0.6527],
           [-0.1307, -0.1275, -0.3603,  1.2101, -0.2131],
           [ 0.1759,  0.3834, -0.3322, -0.2007, -1.3151]]],
 
 
         [[[-0.6924, -0.5323,  0.5774,  0.6957,  1.0399],
           [-0.1325,  0.0276, -0.3515,  0.1618,  0.4912],
           [-0.2195,  1.1915, -0.8961, -0.4367, -3.1768],
           [ 0.1593,  1.1503, -0.1146,  0.8681, -1.4953]],
 
          [[-0.0255, -0.6365, -0.3920,  1.1890,  0.3211],

Tensors are homogeneous, so they allow to have a very compact representation in memory, and allow to perform really fast operations.

## Indexing tensors

In [9]:
t = torch.tensor([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
    ])
t.shape

torch.Size([2, 5])

In [10]:
t[0], t[0].shape

(tensor([1, 2, 3, 4, 5]), torch.Size([5]))

In [11]:
t[1], t[1].shape

(tensor([ 6,  7,  8,  9, 10]), torch.Size([5]))

In [12]:
t[:,0], t[:,0].shape

(tensor([1, 6]), torch.Size([2]))

In [13]:
t[:,1], t[:,1].shape

(tensor([2, 7]), torch.Size([2]))

In [14]:
t

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [15]:
t[:,1:3], t[:,1:3].shape

(tensor([[2, 3],
         [7, 8]]),
 torch.Size([2, 2]))

In [16]:
t[1,::2], t[1,::2].shape

(tensor([ 6,  8, 10]), torch.Size([3]))

## Element types

You can declare the type of a tensor. If not, Torch will infer it

In [17]:
t = torch.tensor([2, 3, 4])
t.dtype

torch.int64

In [18]:
t = torch.tensor([2.5, 3, 4])
t.dtype

torch.float32

In [19]:
torch.tensor([2, 3, 4], dtype=torch.float16)

tensor([2., 3., 4.], dtype=torch.float16)

In [20]:
# you can convert the tensor type using to() method
t = torch.tensor([2, 3, 4])
t2 = t.to(torch.float16)
t.dtype, t2.dtype

(torch.int64, torch.float16)

## Some tensor operations
There are many methods you can use to operate tensors. Some examples:

In [21]:
torch.empty(5, 3)

tensor([[-5.3283e-10,  3.0639e-41, -4.9149e-10],
        [ 3.0639e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  9.1084e-44]])

In [22]:
torch.rand(5, 3)

tensor([[0.6961, 0.4197, 0.0540],
        [0.4919, 0.6510, 0.6171],
        [0.0725, 0.7828, 0.9258],
        [0.0718, 0.6085, 0.5241],
        [0.9391, 0.7488, 0.4917]])

In [23]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.full((4,5),2.3)

tensor([[2.3000, 2.3000, 2.3000, 2.3000, 2.3000],
        [2.3000, 2.3000, 2.3000, 2.3000, 2.3000],
        [2.3000, 2.3000, 2.3000, 2.3000, 2.3000],
        [2.3000, 2.3000, 2.3000, 2.3000, 2.3000]])

In [25]:
torch.ones((3,2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [26]:
x = torch.tensor([[2,3,4], [5,6,7]])
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [27]:
a = torch.arange(0, 12)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a.view((6, 2))

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [ ]:
a.view((2, 6))

In [ ]:
t = a.view((-1, 4))
t

In [ ]:
t.transpose(0, 1)

In [29]:
display(t)
display(t.unsqueeze(0))
t.shape, t.unsqueeze(0).shape

tensor([2, 3, 4])

tensor([[2, 3, 4]])

(torch.Size([3]), torch.Size([1, 3]))

In [ ]:
display(t)
display(t.unsqueeze(1))
t.shape, t.unsqueeze(1).shape

In [ ]:
display(t)
display(t.unsqueeze(2))
t.shape, t.unsqueeze(2).shape

In [30]:
display(t)
display(t.unsqueeze(0))
display(t.unsqueeze(0).squeeze(0))

tensor([2, 3, 4])

tensor([[2, 3, 4]])

tensor([2, 3, 4])

Most of these operations in tensors do not change the memory representation of the data, so they are very fast.

In [ ]:
a = torch.tensor([[2,3,4], [5,6,7]])
b = torch.tensor([[12,13,14], [15,16,17]])
torch.cat([a,b])

In [ ]:
torch.cat([a,b], dim=1)

## Tensor operators

In [31]:
a = torch.ones((3,4)) * 5
a

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [32]:
b = torch.zeros((3,4)) + 3
b

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [33]:
a + b

tensor([[8., 8., 8., 8.],
        [8., 8., 8., 8.],
        [8., 8., 8., 8.]])

In [34]:
a - b

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [35]:
a * b

tensor([[15., 15., 15., 15.],
        [15., 15., 15., 15.],
        [15., 15., 15., 15.]])

In [36]:
a / b

tensor([[1.6667, 1.6667, 1.6667, 1.6667],
        [1.6667, 1.6667, 1.6667, 1.6667],
        [1.6667, 1.6667, 1.6667, 1.6667]])

In [37]:
a**2

tensor([[25., 25., 25., 25.],
        [25., 25., 25., 25.],
        [25., 25., 25., 25.]])

In [38]:
a.sqrt()

tensor([[2.2361, 2.2361, 2.2361, 2.2361],
        [2.2361, 2.2361, 2.2361, 2.2361],
        [2.2361, 2.2361, 2.2361, 2.2361]])

In [39]:
a = torch.rand((4,5))
a

tensor([[0.5167, 0.9030, 0.8340, 0.2409, 0.3679],
        [0.5275, 0.7150, 0.0693, 0.6208, 0.2436],
        [0.3424, 0.9538, 0.6599, 0.4370, 0.4643],
        [0.4647, 0.9910, 0.7784, 0.7699, 0.2962]])

In [40]:
torch.max(a)

tensor(0.9910)

In [41]:
torch.argmax(a)

tensor(16)

### Matrix multiplication

In [42]:
a = torch.rand((3,4))
b = torch.rand((4,2))
a @ b, (a @ b).shape

(tensor([[1.4422, 1.2745],
         [0.9580, 0.6873],
         [1.1901, 0.9798]]),
 torch.Size([3, 2]))

In [ ]:
a = torch.rand((3,5,4))
b = torch.rand((4,2))
(a @ b).shape

In [ ]:
a = torch.rand((1,3,6,5,4))
b = torch.rand((4,9))
(a @ b).shape

## Tensor broadcasting
If an operation expects tensors of same size, the operands can be transformed before to fit.

In [43]:
a = torch.full((2, 3), 3)
b = torch.full((1, 3), 5)
display(a)
display(b)
a+b

tensor([[3, 3, 3],
        [3, 3, 3]])

tensor([[5, 5, 5]])

tensor([[8, 8, 8],
        [8, 8, 8]])

In [44]:
a = torch.full((4, 5), 3)
b = torch.full((4, 1), 5)
display(a)
display(b)
a-b

tensor([[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]])

tensor([[5],
        [5],
        [5],
        [5]])

tensor([[-2, -2, -2, -2, -2],
        [-2, -2, -2, -2, -2],
        [-2, -2, -2, -2, -2],
        [-2, -2, -2, -2, -2]])

In [ ]:
a = torch.tensor([[2,3,4], [5,6,7]])
b = torch.tensor([1,1,1])
display(a)
display(b)
a+b